# Generated by Django 3.1.4 on 2020-12-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('staff', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trans_type', models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit'), (3, 'Delete'), (4, 'Edit')])),
                ('trans_id', models.CharField(max_length=20)),
                ('log', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.IntegerField(choices=[(1, 'membership'), (2, 'unit_payment')])),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('trans_id', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.IntegerField(choices=[(1, 'POS'), (2, 'Transfer'), (3, 'Online')])),
                ('comment', models.CharField(max_length=254)),
                ('sagamy_trans_id', models.IntegerField()),
                ('is_reversed', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
            options={
                'permissions': (('credit_self', 'Can Credit Self'), ('credit_member', 'Can Credit Member')),
            },
        ),
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
        ),
    ]
