# Generated by Django 3.1.4 on 2020-12-11 22:47

import apps.members.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('last_pay_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('business_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('cac', models.FileField(blank=True, null=True, upload_to='', validators=[apps.members.validator.FileValidator(content_types=('image/jpeg', 'application/pdf', 'image/png', 'application/mp4', 'video/mp4', 'audio/mpeg', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'text/plain'), max_size=5242880)])),
                ('valid_id', models.FileField(upload_to='', validators=[apps.members.validator.FileValidator(content_types=('image/jpeg', 'application/pdf', 'image/png', 'application/mp4', 'video/mp4', 'audio/mpeg', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'text/plain'), max_size=5242880)])),
                ('accept_tc', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'permissions': (('activate_member_account', 'Can Activate Member Account'), ('activate_member', 'Can Activate Member'), ('deactivate_member', 'Can De-Activate Member')),
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('validity', models.IntegerField()),
                ('before_tax', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('ref_id', models.CharField(max_length=254, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membershiptype'),
        ),
        migrations.AddField(
            model_name='member',
            name='upgrade_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_type', to='members.membershiptype'),
        ),
        migrations.CreateModel(
            name='CentralDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('docs', models.FileField(upload_to='central_database', validators=[apps.members.validator.FileValidator(content_types=('image/jpeg', 'application/pdf', 'image/png', 'application/mp4', 'video/mp4', 'audio/mpeg', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'text/plain'), max_size=5242880)])),
                ('date', models.DateTimeField(auto_now=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
