# Generated by Django 3.1.4 on 2020-12-11 22:47

import apps.membersite.models
import apps.membersite.validator
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('client', models.CharField(blank=True, max_length=25, null=True)),
                ('desc', models.TextField(help_text='Describe what technology/tools used in achieving clients goal')),
                ('image', models.ImageField(upload_to=apps.membersite.models.firm_directory_path, validators=[apps.membersite.validator.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=5242880)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='MainSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=apps.membersite.models.firm_directory_path, validators=[apps.membersite.validator.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=5242880)])),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('url_identifier', models.CharField(blank=True, help_text='www.enterprisehubs.com/your_business_name', max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook Username eg. enterprise_hubs', max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Facebook Username eg. enterprise_hubs', max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='Facebook Username eg. enterprise_hubs', max_length=50, null=True)),
                ('google_plus', models.CharField(blank=True, help_text='Facebook Username eg. enterprise_hubs', max_length=50, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
