# Generated by Django 3.1.4 on 2020-12-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='Client_Logo')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('whom_to_see', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(choices=[('official', 'Official'), ('visiting', 'Visiting'), ('event', 'Event'), ('others', 'Others')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('how', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('recommendation', 'Recommendation'), ('billboard', 'Billboards')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Testimonial')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPaymentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('ref_id', models.CharField(max_length=254, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.gallerycat')),
            ],
        ),
    ]
