# Generated by Django 3.1.4 on 2020-12-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('book_from', models.DateField()),
                ('book_to', models.DateField(blank=True, null=True)),
                ('is_secured', models.BooleanField(default=False)),
                ('is_hold', models.BooleanField(default=True)),
                ('is_member', models.BooleanField()),
                ('payable_before_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.category')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.unit')),
            ],
            options={
                'permissions': (('view_all_bookings', 'Can view all bookings'), ('approve_bookings', 'Can approve booking')),
            },
        ),
        migrations.CreateModel(
            name='HeldBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.unit')),
            ],
        ),
    ]
